"""
`pe record <name>` — opens a fresh Chromium window in the persistent profile,
navigates to the target URL, and calls `page.pause()` to open the Playwright
Inspector.

Recording flow:
  1. In the inspector, click the red "Record" button.
  2. Do your actions in the Chromium window.
  3. Copy the generated Python snippet from the inspector.
  4. Paste it into `recordings/<name>.py` inside `def run(page, download_dir): ...`.
  5. Close the browser to end the session.

We deliberately do NOT auto-write the recording file — the user reviews and
edits the recorded code before saving, especially to wrap download clicks in
`page.expect_download()`.
"""

from __future__ import annotations

from pathlib import Path

from portfolio_export.config import Config, dated_download_dir
from portfolio_export.session import persistent_context


RECORDING_TEMPLATE = '''"""Recorded flow: {name}

Generated by `pe record {name}`. Edit the body of `run()` with the Python
code Playwright Inspector produced. Wrap any download in
`page.expect_download()` so it saves into `download_dir`. Use the helpers
in `portfolio_export.helpers` to save HTML snapshots or re-check login.
"""

from playwright.sync_api import Page

from portfolio_export.helpers import (
    require_login,
    save_page_html,
    save_page_snapshot,
)

URL = {url!r}


def run(page: Page, download_dir: str) -> list[str]:
    downloaded: list[str] = []

    page.goto(URL)

    # If the persistent profile's session has expired, pause for manual
    # login/MFA. Customize the signal to something that only appears when
    # logged in (URL substring or selector).
    # require_login(page, "/ftgw/digital/portfolio")

    # ---- paste recorded steps below ----
    # page.get_by_role("link", name="Positions").click()
    #
    # # Save the current page as an HTML snapshot (crawler-style):
    # downloaded += [save_page_html(page, download_dir, name="positions")]
    #
    # # Or full snapshot: HTML + screenshot + URL sidecar
    # downloaded += save_page_snapshot(page, download_dir, name="positions_full")
    #
    # # Real file download (e.g. CSV export button):
    # with page.expect_download() as dl_info:
    #     page.get_by_role("button", name="Download").click()
    # dl = dl_info.value
    # dest = f"{{download_dir}}/{{dl.suggested_filename}}"
    # dl.save_as(dest)
    # downloaded.append(dest)
    # ---- end recorded steps ----

    return downloaded
'''


def scaffold_recording(recordings_dir: Path, name: str, url: str) -> Path:
    """Create `<recordings_dir>/<name>.py` from the template if it doesn't exist."""
    recordings_dir.mkdir(parents=True, exist_ok=True)
    target = recordings_dir / f"{name}.py"
    if target.exists():
        return target
    target.write_text(RECORDING_TEMPLATE.format(name=name, url=url), encoding="utf-8")
    return target


def run_record(cfg: Config, name: str, url: str) -> int:
    """Open Chromium + inspector at `url`. User records manually."""
    scaffold_path = scaffold_recording(cfg.user_recordings_dir, name, url)
    download_dir = dated_download_dir(cfg.download_dir)

    print(f"[record] recording name    : {name}")
    print(f"[record] scaffold file     : {scaffold_path}")
    print(f"[record] target URL        : {url}")
    print(f"[record] profile dir       : {cfg.profile_dir}")
    print(f"[record] download dir      : {download_dir}")
    print("[record] Chromium + Playwright Inspector are opening...")
    print("[record] In the inspector, click 'Record' then interact with the site.")
    print("[record] When done, copy the generated Python into the scaffold file.")
    print("[record] Close the browser to finish.")

    # Record must be windowed regardless of PORTFOLIO_EXPORT_HEADLESS.
    with persistent_context(cfg, download_dir=download_dir, headless=False) as ctx:
        page = ctx.new_page()
        page.goto(url)
        # pause() blocks until the user closes the inspector / browser.
        page.pause()

    print(f"[record] session ended. Edit {scaffold_path} with your recorded steps.")
    return 0
