// AnalysisRunner — wires `openbb.runAnalysis` (#1828) to the 7-phase
// pipeline in Analysis/stock_analysis.py by opening a fresh
// workspace-local notebook built from a template. Per PRD Q6, we do
// NOT modify the checked-in notebooks in notebooks/portfolio/.

import * as vscode from "vscode";
import { spawn as realSpawn } from "child_process";

export const SYMBOL_RE = /^[A-Z]{1,5}(:[A-Z]+)?$/;

export type SpawnLike = (
  cmd: string,
  args: string[],
  opts: unknown,
) => {
  stdout: { on(evt: "data", cb: (chunk: Buffer | string) => void): void };
  stderr: { on(evt: "data", cb: (chunk: Buffer | string) => void): void };
  on(evt: "close" | "error", cb: (arg: unknown) => void): void;
  kill(): void;
};

export interface AnalysisRunnerConfig {
  pythonPath?: string;
  workspaceRoot?: string;
  outputChannel: Pick<vscode.OutputChannel, "appendLine">;
  spawnImpl?: SpawnLike;
}

export interface EnsureResult {
  ok: boolean;
  message: string;
}

export interface RunResult {
  notebookUri: vscode.Uri | null;
  error?: string;
}

export function buildAnalysisNotebookCells(symbol: string): {
  kind: number;
  language: string;
  value: string;
}[] {
  return [
    {
      kind: 1,
      language: "markdown",
      value:
        `# 7-Phase Analysis — ${symbol}\n\n` +
        "Generated by openbb.runAnalysis. Underlying pipeline: " +
        "Analysis/stock_analysis.py",
    },
    {
      kind: 2,
      language: "python",
      value:
        "from stock_analysis import AnalysisConfig, run_full_analysis\n" +
        `results = run_full_analysis(AnalysisConfig(symbol="${symbol}"))\n` +
        'p7 = results["p7"]\n' +
        "print(p7.action_label, p7.composite_score)",
    },
    {
      kind: 2,
      language: "python",
      value:
        "# Phase-by-phase results\n" +
        'for phase in ("p1","p2","p3","p4","p5","p6","p7"):\n' +
        "    print(phase, results[phase])",
    },
  ];
}

export class AnalysisRunner {
  private readonly cfg: AnalysisRunnerConfig;
  private readonly spawnImpl: SpawnLike;

  constructor(cfg: AnalysisRunnerConfig) {
    this.cfg = cfg;
    this.spawnImpl = cfg.spawnImpl ?? (realSpawn as unknown as SpawnLike);
  }

  resolvePython(): string {
    const raw = this.cfg.pythonPath;
    const resolved =
      typeof raw === "string" && raw.trim().length > 0 ? raw.trim() : "python";
    if (typeof resolved !== "string" || resolved.length === 0) {
      throw new Error("resolvePython: interpreter path is not a valid string");
    }
    return resolved;
  }

  async ensureAnalysisModule(): Promise<EnsureResult> {
    const python = this.resolvePython();
    return await new Promise<EnsureResult>((resolve) => {
      let done = false;
      const finish = (r: EnsureResult): void => {
        if (done) return;
        done = true;
        resolve(r);
      };
      let stdout = "";
      let stderr = "";
      let child: ReturnType<SpawnLike>;
      try {
        child = this.spawnImpl(
          python,
          ["-c", "import stock_analysis; print('ok')"],
          { windowsHide: true },
        );
      } catch (e) {
        finish({
          ok: false,
          message:
            "Analysis/ module not found in this Python — run pip install " +
            `-e Analysis (spawn error: ${String(e)})`,
        });
        return;
      }
      const timer = setTimeout(() => {
        try {
          child.kill();
        } catch {
          /* noop */
        }
        finish({
          ok: false,
          message:
            "Analysis/ module check timed out after 5s — run pip install " +
            "-e Analysis to verify the interpreter can import stock_analysis",
        });
      }, 5000);
      child.stdout.on("data", (c) => {
        stdout += String(c);
      });
      child.stderr.on("data", (c) => {
        stderr += String(c);
      });
      child.on("error", (err) => {
        clearTimeout(timer);
        finish({
          ok: false,
          message:
            "Analysis/ module not found in this Python — run pip install " +
            `-e Analysis (spawn error: ${String(err)})`,
        });
      });
      child.on("close", (code) => {
        clearTimeout(timer);
        if (code === 0 && stdout.includes("ok")) {
          finish({ ok: true, message: stdout.trim() });
        } else {
          finish({
            ok: false,
            message:
              "Analysis/ module not found in this Python — run pip install " +
              `-e Analysis (exit=${String(code)}; stderr=${stderr.trim()})`,
          });
        }
      });
    });
  }

  async runForSymbol(symbol: string): Promise<RunResult> {
    if (!SYMBOL_RE.test(symbol)) {
      return {
        notebookUri: null,
        error: `Invalid symbol: "${symbol}" (expected e.g. AAPL or AAPL:NASDAQ)`,
      };
    }
    const ensured = await this.ensureAnalysisModule();
    if (!ensured.ok) {
      this.cfg.outputChannel.appendLine(
        `[analysis] ensureAnalysisModule failed: ${ensured.message}`,
      );
      return { notebookUri: null, error: ensured.message };
    }

    const cells = buildAnalysisNotebookCells(symbol);
    const notebookCells = cells.map(
      (c) => new vscode.NotebookCellData(c.kind, c.value, c.language),
    );
    const data = new vscode.NotebookData(notebookCells);
    data.metadata = {
      custom: {
        kernelspec: {
          display_name: "Python 3",
          language: "python",
          name: "python3",
        },
        language_info: { name: "python" },
      },
    };

    try {
      const doc = await vscode.workspace.openNotebookDocument(
        "jupyter-notebook",
        data,
      );
      await vscode.window.showNotebookDocument(doc);
      return { notebookUri: doc.uri };
    } catch (e) {
      const msg = `Failed to open analysis notebook: ${String(e)}`;
      this.cfg.outputChannel.appendLine(`[analysis] ${msg}`);
      return { notebookUri: null, error: msg };
    }
  }
}
