"""Two-provider coverage audit + report generator (Wave 0 A1 / #1314).

Extends the fmp_cached coverage gate to also audit ``openbb_fmp``.
Emits ``docs/reports/fmp-two-provider-coverage.md`` so downstream
wave-task contributors can see at a glance:

- endpoints registered in ``openbb_fmp`` but NOT wrapped by
  ``openbb_fmp_cached`` (candidates for downstream wave tasks)
- endpoints registered in either provider that lack a VCR cassette
- endpoints that are plan-limited (see ``plan_limited.py``) — these
  are NOT gaps; they're documented tier-blocks.

Design notes:
- The test emits the report on every run so it stays current with the
  fetcher_dict registration state. The report is checked into
  ``docs/reports/`` so a stale copy shows up in git diff (loud signal
  that someone added an endpoint without running tests).
- The test asserts the report was generated (no silent skip); the gate
  itself is the coverage delta, not the report file.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from openbb_fmp_cached.utils.plan_limited import _PLAN_LIMITED, is_plan_limited

_REPO_ROOT = Path(__file__).resolve().parents[4]
_REPORT_PATH = _REPO_ROOT / "docs" / "reports" / "fmp-two-provider-coverage.md"
_CASSETTE_DIR = Path(__file__).parent / "record" / "http" / "test_fmp_cached_fetchers"


def _fmp_endpoints() -> set[str]:
    """Return the set of registered fetcher names in openbb_fmp."""
    from openbb_fmp import fmp_provider

    return set(fmp_provider.fetcher_dict.keys())


def _fmp_cached_endpoints() -> set[str]:
    """Return the set of registered fetcher names in openbb_fmp_cached."""
    from openbb_fmp_cached import fmp_cached_provider

    return set(fmp_cached_provider.fetcher_dict.keys())


def _endpoint_to_test_stem(endpoint: str) -> str:
    """Convert a CamelCase endpoint name to the snake_case test-fn suffix used by cassettes."""
    overrides = {
        "EquityInfo": "equity_profile",
        "CashFlowStatement": "cash_flow",
        "CashFlowStatementGrowth": "cash_flow_growth",
    }
    if endpoint in overrides:
        return overrides[endpoint]
    out = []
    for i, c in enumerate(endpoint):
        if c.isupper() and i > 0:
            out.append("_")
        out.append(c.lower())
    return "".join(out)


def _has_cassette(endpoint: str) -> bool:
    stem = _endpoint_to_test_stem(endpoint)
    return bool(list(_CASSETTE_DIR.glob(f"test_fmp_cached_{stem}_fetcher_*.yaml")))


def _build_report() -> str:
    fmp = _fmp_endpoints()
    fmp_cached = _fmp_cached_endpoints()

    only_in_fmp = fmp - fmp_cached
    only_in_cached = fmp_cached - fmp
    in_both = fmp & fmp_cached
    lack_cassette = {e for e in (fmp | fmp_cached) if not _has_cassette(e)}
    plan_limited = set(_PLAN_LIMITED)

    lines = [
        "# FMP Two-Provider Coverage Report",
        "",
        "> Auto-generated by `tests/test_two_provider_coverage.py` on every test run.",
        "> Stale copy in git diff = someone added an endpoint without running tests.",
        "",
        "## Summary",
        "",
        f"- `openbb_fmp` registered endpoints: **{len(fmp)}**",
        f"- `openbb_fmp_cached` registered endpoints: **{len(fmp_cached)}**",
        f"- Registered in both: **{len(in_both)}**",
        f"- Registered in `openbb_fmp` only (downstream wave candidates): **{len(only_in_fmp)}**",
        f"- Registered in `openbb_fmp_cached` only (native, no upstream wrap): **{len(only_in_cached)}**",
        f"- Registered in EITHER but lacking a VCR cassette: **{len(lack_cassette)}**",
        f"- Plan-limited (see `plan_limited.py`): **{len(plan_limited)}**",
        "",
        "## Endpoints in `openbb_fmp` only (candidates for downstream wave wrappers)",
        "",
    ]
    if only_in_fmp:
        for e in sorted(only_in_fmp):
            marker = " *(plan-limited)*" if is_plan_limited(e) else ""
            cassette = " ✅ cassette" if _has_cassette(e) else ""
            lines.append(f"- `{e}`{marker}{cassette}")
    else:
        lines.append("_(none — every fmp fetcher has an fmp_cached wrapper)_")

    lines.extend(
        [
            "",
            "## Endpoints in `openbb_fmp_cached` only (native fetchers, no `openbb_fmp` peer)",
            "",
        ]
    )
    if only_in_cached:
        for e in sorted(only_in_cached):
            cassette = " ✅ cassette" if _has_cassette(e) else " ⚠ no cassette"
            lines.append(f"- `{e}`{cassette}")
    else:
        lines.append("_(none)_")

    lines.extend(
        [
            "",
            "## Missing cassettes (registered but no fixture — gaps for the coverage test)",
            "",
        ]
    )
    if lack_cassette:
        for e in sorted(lack_cassette):
            markers = []
            if is_plan_limited(e):
                markers.append("plan-limited")
            if e in only_in_fmp:
                markers.append("fmp-only")
            elif e in only_in_cached:
                markers.append("cached-only")
            else:
                markers.append("both")
            lines.append(f"- `{e}` — {', '.join(markers)}")
    else:
        lines.append("_(none — every registered endpoint has a cassette)_")

    lines.extend(
        [
            "",
            "## Plan-limited endpoints (permanent — do NOT try to record)",
            "",
        ]
    )
    for e in sorted(plan_limited):
        entry = _PLAN_LIMITED[e]
        lines.append(
            f"- `{e}` — tier: `{entry['tier']}`, since: {entry['since']}, notes: {entry['notes']}"
        )

    lines.append("")
    return "\n".join(lines)


def test_two_provider_coverage_report_is_regenerated():
    """Regenerate the two-provider coverage report on every test run.

    The regeneration IS the discriminator: a stale report in git diff
    tells the reviewer someone added an endpoint without touching the
    tests.
    """
    report = _build_report()
    _REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    _REPORT_PATH.write_text(report, encoding="utf-8", newline="\n")
    # Sanity: the report is non-empty and cites the summary section.
    assert "## Summary" in report
    assert "openbb_fmp_cached" in report


def test_plan_limited_registry_shape():
    """Every _PLAN_LIMITED entry MUST have tier + since + notes."""
    from datetime import date

    for endpoint, entry in _PLAN_LIMITED.items():
        assert (
            isinstance(endpoint, str) and endpoint
        ), "empty endpoint key in _PLAN_LIMITED"
        assert (
            isinstance(entry.get("tier"), str) and entry["tier"]
        ), f"{endpoint}: tier must be a non-empty str"
        assert isinstance(
            entry.get("since"), date
        ), f"{endpoint}: since must be a datetime.date"
        assert (
            isinstance(entry.get("notes"), str) and entry["notes"]
        ), f"{endpoint}: notes must be a non-empty str"


def test_is_plan_limited_returns_bool():
    """is_plan_limited returns True for a seeded endpoint, False otherwise."""
    assert is_plan_limited("EsgScore") is True
    assert is_plan_limited("EquityHistorical") is False
    assert is_plan_limited("NotARealEndpoint") is False


@pytest.mark.parametrize(
    "endpoint",
    ["CryptoSearch", "EsgScore", "MarketSnapshots"],
)
def test_seeded_endpoints_still_registered(endpoint: str):
    """If a seeded plan-limited endpoint stops being registered, the seed is stale."""
    if endpoint not in (_fmp_endpoints() | _fmp_cached_endpoints()):
        pytest.fail(
            f"{endpoint} is in _PLAN_LIMITED but no longer registered in "
            "either provider — remove the entry."
        )
