"""Batch-create bd tasks for Portfolio Intelligence execution plan.

Reads phase IDs from /tmp/pi_ids, then shells `bd create --silent` per task.
Uses subprocess with a list of args (no shell) so apostrophes are safe.
"""
import subprocess, sys, os

# Hardcoded phase IDs (from earlier bd create --silent output)
M0 = "OpenBBTechnical-qy83.1"
P0 = "OpenBBTechnical-qy83.2"
P1 = "OpenBBTechnical-qy83.3"
P2 = "OpenBBTechnical-qy83.4"
P3 = "OpenBBTechnical-qy83.5"

def mk(parent, labels, desc, title):
    args = [
        "bd", "create", "--silent",
        "-t", "task", "-p", "0",
        "--parent", parent,
        "-l", labels,
        "-d", desc,
        title,
    ]
    r = subprocess.run(args, capture_output=True, text=True)
    if r.returncode != 0:
        print("FAIL:", title, file=sys.stderr)
        print(r.stderr, file=sys.stderr)
        return None
    # bd may still print warnings on stderr; the id is on stdout
    return r.stdout.strip().splitlines()[-1] if r.stdout.strip() else None

tasks = []

# ================ M0 ================
tasks += [
    (M0, "portfolio-intel,m0,lane-pm",
     "Cut portfolio branch off develop. Enable branch protection: PRs required, CI required, no direct commits, no force-push. Branch protection on develop requires PM + senior review to prevent accidental early merge from any feat/pi-* branch.",
     "[M0] Cut portfolio branch + branch protection (portfolio & develop)"),
    (M0, "portfolio-intel,m0,lane-pm",
     "Add .github/pull_request_template.md that defaults PR base to portfolio for feat/pi-* branches. Add CI check that rejects feat/pi-* PRs targeting develop or main.",
     "[M0] PR template + CI rule: feat/pi-* must target portfolio"),
    (M0, "portfolio-intel,m0,lane-pm",
     "Schedule Monday portfolio-onto-develop rebase cadence per Execution Plan section 2A.4. Add to shared calendar. PM owns. If conflict emerges, E1/E2/E3/E4 pair same day.",
     "[M0] Schedule weekly Monday portfolio<-develop sync (PM owned)"),
    (M0, "portfolio-intel,m0,lane-b",
     "Scaffold openbb_platform/extensions/portfolio_intel/ (router.py, models, __init__.py, tests). Wire into openbb_platform build; CI green on portfolio. Base branch: portfolio.",
     "[M0] Scaffold portfolio_intel extension skeleton (CI green)"),
    (M0, "portfolio-intel,m0,lane-c",
     "Draft migration file for paper_* tables (paper_accounts, paper_orders, paper_fills, paper_positions, paper_ledger) per PRD section 16.3. Reviewed by E1 + E3. Not applied until P2.",
     "[M0] Draft paper_* migration file (reviewed by E1+E3)"),
    (M0, "portfolio-intel,m0,lane-a",
     "Create tests/fixtures/fmp/ dir + fixture-record CLI. Documented in README. Every 32 fmp_cached model ships with a recorded HTTP fixture so E2/E3 tests never hit live FMP.",
     "[M0] Recorded-fixture harness for FMP (tests/fixtures/fmp/)"),
    (M0, "portfolio-intel,m0,lane-d",
     "Add Playwright harness to portfolio_app/tests/e2e/. Widget contract test skeleton. 3 placeholder widgets hitting stub endpoints for E2E smoke.",
     "[M0] Playwright E2E harness + widget scaffolds"),
    (M0, "portfolio-intel,m0,lane-qa",
     "Author paper-account isolation test spec per PRD section 16.6 + Execution Plan section 19. Merged as pending/skipped test so it survives to P2 unchanged. Any query returning cross-account row = fail.",
     "[M0] QA: author cross-account isolation test spec (pending)"),
    (M0, "portfolio-intel,m0,lane-pm",
     "Every engineer runs shared-env smoke test from their worktree root (see Execution Plan Appendix A). Green loader before any Lane A/B/C work starts.",
     "[M0] Shared .env smoke test green from every worktree"),
    (M0, "portfolio-intel,m0,lane-pm",
     "Decide PRD Q8: paper fill model — ship SimpleFillModel inline OR wait on openbb-backtest exposing a shared execution primitive? Must be resolved and PRD updated before P2 staffing.",
     "[M0] DECISION: Resolve PRD Q8 (paper fill model source)"),
    (M0, "portfolio-intel,m0,lane-pm",
     "Book gate reviews on calendar: M1 (end Wk 3), M2 (end Wk 8), M3 (end Wk 13), M4 (end Wk 16). Attendees: 4 engineers + PM + QA + Backtest PRD rep + Quant PRD rep. Written go/no-go required.",
     "[M0] Book M1/M2/M3/M4 gate reviews (60 min each)"),
]

# ================ P0 (Data layer) ================
tasks += [
    (P0, "portfolio-intel,p0,lane-a",
     "First reference model. Pydantic + SQLAlchemy + gap-detection + round-trip test + recorded fixture. Feeds X-Ray look-through (PRD section 11). MUST land end of Wk 1 — unblocks all of Lane B.",
     "[P0][Data] EtfHoldings model (etf/holdings) — PRIORITY, unblocks Lane B"),
    (P0, "portfolio-intel,p0,lane-a",
     "etf/info + etf/sector-weightings + etf/country-weightings. Completes the ETF look-through data quartet. Feeds X-Ray sector/country rollups.",
     "[P0][Data] EtfInfo + EtfSectorWeightings + EtfCountryWeightings"),
    (P0, "portfolio-intel,p0,lane-a",
     "earnings-calendar + dividends-calendar + splits-calendar + ipos-calendar. Feeds Event Calendar (PRD section 12).",
     "[P0][Data] Calendars: Earnings + Dividends + Splits + IPOs"),
    (P0, "portfolio-intel,p0,lane-a",
     "analyst-estimates + ratings-snapshot + price-target-consensus + grades-consensus. Feeds Analyst Sentiment widget (PRD section 9.9).",
     "[P0][Data] Analyst: Estimates + Ratings + PriceTarget + UpgradesDowngrades"),
    (P0, "portfolio-intel,p0,lane-a",
     "insider-trading/latest + insider-trading/search + insider-trading/statistics. Feeds Smart-Money overlay (PRD section 13).",
     "[P0][Data] InsiderTrades (Latest + Search + Statistics)"),
    (P0, "portfolio-intel,p0,lane-a",
     "institutional-ownership/extract + institutional-ownership/holder-performance-summary. Filtered-by-held-CUSIPs in P1 (not bulk) to control disk footprint. Feeds Smart-Money.",
     "[P0][Data] Form 13F (Extract + Holder Performance Summary)"),
    (P0, "portfolio-intel,p0,lane-a",
     "senate-latest + senate-trading. Neutral display; no party emphasis. Feeds Smart-Money.",
     "[P0][Data] Senate Disclosures (Latest + Trading)"),
    (P0, "portfolio-intel,p0,lane-a",
     "sec-filings-search + sec-filings-company-search + sec-filings-8-k. Feeds material-event alerts + News widget.",
     "[P0][Data] SEC Filings (Search + Company Search + 8-K)"),
    (P0, "portfolio-intel,p0,lane-a",
     "news/stock + news/press-releases + news/general-latest. Windowed retention policy documented. Feeds Portfolio News widget.",
     "[P0][Data] News (Stock + Press Releases + General Latest)"),
    (P0, "portfolio-intel,p0,lane-a",
     "economic-calendar + treasury-rates + economic-indicators. Feeds macro-event overlay on Event Calendar.",
     "[P0][Data] Economics (Calendar + Treasury Rates + Indicators)"),
    (P0, "portfolio-intel,p0,lane-a",
     "sector-performance-snapshot + industry-performance-snapshot + biggest-gainers + biggest-losers. Feeds context bars around portfolio return.",
     "[P0][Data] Market Performance (Sector + Industry + Gainers/Losers)"),
    (P0, "portfolio-intel,p0,lane-a",
     "technical-indicators/* endpoints wired. Per-holding technical strip in X-Ray widget.",
     "[P0][Data] Technical Indicators endpoints (per-holding strip)"),
    (P0, "portfolio-intel,p0,lane-a",
     "New table portfolio_intel_cache per PRD section 10.2. Key: (portfolio_hash CHAR(64), as_of_date DATE, endpoint VARCHAR(64)). Hash is SHA-256 of sorted (symbol, qty) tuples — NEVER account/owner/lot. TTL enforcement per surface. Automated schema test asserts no PII columns.",
     "[P0][Data] Derived-analytics cache table (portfolio_intel_cache)"),
    (P0, "portfolio-intel,p0,lane-a",
     "Prebuilt warmers for top-100 ETFs and S&P500 constituents. Runs on demand or nightly. Reduces cold-cache p95 for X-Ray from ~4s to <1s in demo scenarios.",
     "[P0][Data] Cache warmers for common ETFs + S&P500 constituents"),
]

# ================ P1 ================
tasks += [
    (P1, "portfolio-intel,p1,lane-b",
     "PRD section 11. Recursive unwrap (max depth 2). Warnings for unresolved funds + stale holdings (>90d). Unit tests: pure equity, 100% ETF, ETF-of-ETFs, unknown fund. Deterministic output.",
     "[P1][Analytics] X-Ray look-through algorithm (recursive unwrap)"),
    (P1, "portfolio-intel,p1,lane-b",
     "Rollups: by sector (GICS), industry, country, market-cap bucket, single-name top-25, overlap matrix. Pure-function, unit-tested.",
     "[P1][Analytics] X-Ray rollups (sector/country/mcap/overlap)"),
    (P1, "portfolio-intel,p1,lane-b",
     "HHI, top-10 weight, effective N, single-name-risk table. PRD section 9.2.",
     "[P1][Analytics] Concentration + HHI endpoint"),
    (P1, "portfolio-intel,p1,lane-b",
     "PRD section 12. Union of 5 streams (earnings/div/splits/IPO/macro) dedup on (symbol,date,event_type). Timeline-widget-shaped output.",
     "[P1][Analytics] Event Calendar merge algorithm"),
    (P1, "portfolio-intel,p1,lane-b",
     "PRD section 13. Per-position insider net-activity 30/90/180d; 13F holder-count delta; top-3 holder performance; senate-trades 90d. Portfolio-level weighted score.",
     "[P1][Analytics] Smart-Money aggregator (insider+13F+senate)"),
    (P1, "portfolio-intel,p1,lane-b",
     "PRD section 14.1. Sharpe/Sortino/VaR/CVaR/MaxDD/Ulcer/Beta/Alpha at portfolio level. Share math with Analysis/stock_analysis.compute_risk_kpis — SINGLE source of truth. Rolling 60d vol series.",
     "[P1][Analytics] Portfolio risk metrics (shared math with Analysis/)"),
    (P1, "portfolio-intel,p1,lane-b",
     "PRD section 14.2. Marginal VaR + component VaR + component beta + component vol per position. Property test: components sum to totals.",
     "[P1][Analytics] Contribution-to-risk (marginal + component VaR)"),
    (P1, "portfolio-intel,p1,lane-c",
     "portfolio_app/src/intel.py wires GET /portfolio/intel/xray. Joins portfolio_basket with obb.etf.holdings and obb.portfolio.intel.xray. JSON contract fixtures for E4.",
     "[P1][App] /portfolio/intel/xray route + portfolio_basket join"),
    (P1, "portfolio-intel,p1,lane-c",
     "GET /portfolio/intel/events?days=30 endpoint. Timeline shape validated against widget contract. Filter to held symbols only.",
     "[P1][App] /portfolio/intel/events route (timeline shape)"),
    (P1, "portfolio-intel,p1,lane-c",
     "GET /portfolio/intel/smart_money?window=90d endpoint. Roll-up + per-position ribbon shape.",
     "[P1][App] /portfolio/intel/smart_money route (rollup)"),
    (P1, "portfolio-intel,p1,lane-c",
     "GET /portfolio/intel/risk?benchmark=SPY + GET /portfolio/intel/concentration endpoints. Latency budget: warm <600ms.",
     "[P1][App] /portfolio/intel/risk + /concentration routes"),
    (P1, "portfolio-intel,p1,lane-d",
     "Two widget entries in portfolio_app/widgets.json: X-Ray Sector (pie) + X-Ray Country (pie). Playwright test: renders live against warm cache.",
     "[P1][Widgets] X-Ray Sector + Country pie widgets"),
    (P1, "portfolio-intel,p1,lane-d",
     "Look-Through Top-25 (table). Concentration & HHI (number + gauge). Both wire to existing endpoints.",
     "[P1][Widgets] Look-Through Top-25 table + Concentration gauge"),
    (P1, "portfolio-intel,p1,lane-d",
     "Event Calendar timeline widget with drill-down. Uses /portfolio/intel/events.",
     "[P1][Widgets] Event Calendar timeline widget"),
    (P1, "portfolio-intel,p1,lane-d",
     "Smart-Money ribbon widget (table). SHARED PAPER-badge component (reused throughout P2). Even though M2 does not ship paper accounts, the badge component must land here so E4 does not scramble in P2.",
     "[P1][Widgets] Smart-Money ribbon + SHARED PAPER-badge component"),
    (P1, "portfolio-intel,p1,lane-d",
     "Risk Dashboard widget: number-grid (Sharpe/Sortino/VaR/CVaR/MaxDD/Ulcer/Beta/Alpha) + rolling 60d vol chart. Contribution-to-risk drill-down.",
     "[P1][Widgets] Risk Dashboard widget (number-grid + vol chart)"),
    (P1, "portfolio-intel,p1,lane-d",
     "M2 demo build: 8-widget Phase-1 dashboard renders end-to-end against a real portfolio. Playwright green. Recorded demo cut for leadership. Gate review on last day of Wk 8.",
     "[P1][Demo] M2 build + recorded demo cut"),
]

# ================ P2 ================
tasks += [
    (P2, "portfolio-intel,p2,lane-a",
     "indexes/historical-constituents for SPY/QQQ/IWM/ACWI. Required for Brinson attribution. Nightly refresh job.",
     "[P2][Data] Index-constituent history (SPY/QQQ/IWM/ACWI)"),
    (P2, "portfolio-intel,p2,lane-a",
     "Nightly reconciliation: cross-check paper_ledger vs dividends-calendar and splits-calendar. Credit ex-dividend cash; apply split adjustments to paper_positions. Silent P&L drift = fail.",
     "[P2][Data] Corporate-action reconciler (nightly job)"),
    (P2, "portfolio-intel,p2,lane-a",
     "QA-owned reference values for Brinson attribution. Sourced from 2 independent references (Bloomberg + hand spreadsheet). Tolerances documented (+/-1bp allocation, +/-1bp selection).",
     "[P2][Data/QA] Brinson reference fixtures (Bloomberg + spreadsheet)"),
    (P2, "portfolio-intel,p2,lane-b",
     "PRD section 15. Stateless: accept positions + candidate deltas, return diff view of X-Ray/concentration/risk. NO writes to any table. Composable in-memory.",
     "[P2][Analytics] What-If diff engine (stateless)"),
    (P2, "portfolio-intel,p2,lane-b",
     "PRD section 14.3. Two-factor decomposition (allocation vs selection effect) per sector, over 1M/3M/6M/1Y windows. Requires index-constituent history. MUST match Brinson reference fixtures to +/-1bp.",
     "[P2][Analytics] Brinson-Fachler attribution (allocation vs selection)"),
    (P2, "portfolio-intel,p2,lane-b",
     "Waterfall response shape optimized for widget render. Sums to active return (property test).",
     "[P2][Analytics] Attribution waterfall response shape"),
    (P2, "portfolio-intel,p2,lane-b",
     "PRD section 16.9. paper.account.export_backtest command generates openbb-backtest trade list from paper_fills. Feature-flagged fallback: JSON dump if backtest engine not yet available.",
     "[P2][Analytics] Backtest hand-off contract (paper.account.export_backtest)"),
    (P2, "portfolio-intel,p2,lane-c",
     "Apply paper_* migration (drafted in M0). Enable per-account API. Commands: create, list, get, reset, delete per PRD section 16.5.",
     "[P2][Paper] Apply paper_* migration + account CRUD"),
    (P2, "portfolio-intel,p2,lane-c",
     "PRD section 16.4. Order types: market, limit. TIF: day, gtc. Quote source: obb.equity.price.quote via fmp_cached with 60s freshness check. Default 5 bps slippage. Property tests. E2 named as backup owner per Exec Plan risk register.",
     "[P2][Paper][Fills v0] Market + Limit orders; TIF day/gtc"),
    (P2, "portfolio-intel,p2,lane-c",
     "Stop + stop_limit + trailing_stop (peak-tracking). Partial fills modeled if qty/ADV < 0.5%. IOC/FOK behavior. TIF expiry via exchange calendar.",
     "[P2][Paper][Fills v1] Stop / Stop-Limit / Trailing-Stop + partials"),
    (P2, "portfolio-intel,p2,lane-c",
     "PRD section 16.3. Append-only journal. entry_types: trade, dividend, split, fee, deposit, withdraw. paper.account.replay reconstructs state from ledger — replay test asserts live state == replay state.",
     "[P2][Paper] Ledger + replay endpoint (append-only journal)"),
    (P2, "portfolio-intel,p2,lane-c",
     "SEV-1 gate. Automated test: no query returns cross-account row (paper<->real or paper<->paper). Server-side rule: paper responses cannot be aliased under a real-account ID. SQL-grep test enforces portfolio_basket / paper_* separation. QA sign-off required.",
     "[P2][Paper] Cross-account ISOLATION enforcement + tests (SEV-1)"),
    (P2, "portfolio-intel,p2,lane-c",
     "Race conditions in fill engine; single-writer-per-account_id lock ordering documented; explicit deadlock avoidance.",
     "[P2][Paper] Fill-engine hardening: races + lock ordering"),
    (P2, "portfolio-intel,p2,lane-c",
     "Cost-basis + P&L computed by SAME functions as real portfolio_app service. Shared module + unit tests asserting parity. Prevents divergence risk (Exec Plan Risk Register).",
     "[P2][Paper] Shared cost-basis/P&L math with real service"),
    (P2, "portfolio-intel,p2,lane-d",
     "Order Ticket widget: form + two-step confirm dialog. PAPER badge + tint. Submits to POST /portfolio/intel/paper/order/submit.",
     "[P2][Widgets] Paper Order Ticket widget (form + 2-step confirm)"),
    (P2, "portfolio-intel,p2,lane-d",
     "Blotter widget: order table (open/filled/cancelled/rejected). Filter + sort. PAPER badge throughout. Uses /portfolio/intel/paper/order/list.",
     "[P2][Widgets] Paper Blotter widget (order table)"),
    (P2, "portfolio-intel,p2,lane-d",
     "Performance widget: equity curve + KPI grid (Sharpe/Sortino/DD/return). Uses /portfolio/intel/paper/performance. PAPER badge + explicit fill-assumption disclaimer per PRD section 21.",
     "[P2][Widgets] Paper Performance widget (equity curve + KPIs)"),
    (P2, "portfolio-intel,p2,lane-d",
     "What-If diff card widget: interactive; before/after side-by-side for X-Ray/concentration/risk. Diff shape from Lane B endpoint.",
     "[P2][Widgets] What-If diff card widget (interactive)"),
    (P2, "portfolio-intel,p2,lane-d",
     "Brinson Attribution waterfall widget. Sums to active return visibly. Wire to /portfolio/intel/attribution.",
     "[P2][Widgets] Brinson Attribution waterfall widget"),
    (P2, "portfolio-intel,p2,lane-d",
     "PAPER account grouping in Workspace account selector: real accounts above, divider, paper below. Enforced separation in UI, not just API. Every widget rendering a paper account shows PAPER badge + distinct background tint.",
     "[P2][UX] PAPER badge + separate account-selector group"),
    (P2, "portfolio-intel,p2,lane-d",
     "M3 demo: submit paper limit order -> fill -> X-Ray on paper account renders with the new position. Every intelligence widget works against paper via ?account_id=paper_*. Gate review last day of Wk 13.",
     "[P2][Demo] M3 build + gate demo (paper order round-trip)"),
]

# ================ P3 ================
tasks += [
    (P3, "portfolio-intel,p3,lane-a",
     "Query-index review on news + 8-K tables for alert-relevant patterns (severity>=material, held-symbol filter). Ensures alert rule engine hits index.",
     "[P3][Data] News/8-K query index tuning + alert indices"),
    (P3, "portfolio-intel,p3,lane-b",
     "PRD section 9.9. Weighted analyst rating, price-target upside, recent upgrades/downgrades per holding, rolled up to portfolio.",
     "[P3][Analytics] Sentiment rollup (weighted analyst + PT upside)"),
    (P3, "portfolio-intel,p3,lane-b",
     "PRD section 17 Phase 1. In-widget alert panel with 6 trigger types: earnings <=5d, ex-div <=5d, insider open-market buy >$100K, 8-K for held symbol, analyst downgrade for top-10 holding, paper-trading events.",
     "[P3][Analytics] Alert-rule engine (6 trigger types)"),
    (P3, "portfolio-intel,p3,lane-c",
     "GET /portfolio/intel/news + GET /portfolio/intel/sentiment endpoints. Merged news+PR+8-K stream; filter by severity.",
     "[P3][App] /portfolio/intel/news + /sentiment routes"),
    (P3, "portfolio-intel,p3,lane-c",
     "Wire obb.backtest.portfolio(weights=..., start=..., end=...) via openbb_client.py. Feature-flagged fallback to JSON dump if openbb-backtest not yet available.",
     "[P3][App] Backtest hand-off wire-up (obb.backtest.portfolio)"),
    (P3, "portfolio-intel,p3,lane-c",
     "Alert-rule wiring on paper_* events: order filled, stop triggered, GTC expiring soon, buying power <10% of equity. Fires into same alert panel as market events.",
     "[P3][App] Paper-trading alert wiring (fills, stops, TIF, BP)"),
    (P3, "portfolio-intel,p3,lane-d",
     "News widget (list) + Sentiment widget (table). Both wire to P3 endpoints.",
     "[P3][Widgets] News + Sentiment widgets"),
    (P3, "portfolio-intel,p3,lane-d",
     "Alert panel component with subscription plumbing. Renders 6 trigger types; groups by priority/date. Pinned to Event Calendar + Smart-Money widgets per PRD section 17.",
     "[P3][Widgets] Alert panel component (pinned in existing widgets)"),
    (P3, "portfolio-intel,p3,lane-d",
     "One-click Backtest this portfolio / this paper account button in Risk Dashboard + Blotter. Opens openbb-backtest with correct payload.",
     "[P3][Widgets] One-click Backtest-this-portfolio button"),
    (P3, "portfolio-intel,m4,lane-pm",
     "Portfolio branch fully green on nightly CI for 3 consecutive nights BEFORE opening the M4 merge PR. Non-negotiable.",
     "[M4] Nightly CI green on portfolio for 3 consecutive nights"),
    (P3, "portfolio-intel,m4,lane-b",
     "Full APIEx + PythonEx examples for every command; user-facing docs page; release notes; internal changelog. Per Definition of Done Lane B.",
     "[M4] Documentation + release notes + APIEx/PythonEx complete"),
    (P3, "portfolio-intel,m4,lane-pm",
     "Per Execution Plan section 2A.5. Final rebase portfolio onto develop; full CI + Playwright green on rebased tip; tag pi-rc-1; single PR into develop with merge-commit (NOT squash) to preserve per-ticket history; PM+E2 own.",
     "[M4] Rebase portfolio onto develop + cut pi-rc-1 tag"),
    (P3, "portfolio-intel,m4,lane-pm",
     "The single portfolio->develop integration PR. Merged with merge-commit. Includes bd epic close. FIRST AND ONLY develop touch of this program.",
     "[M4] SINGLE portfolio->develop integration PR (merge-commit)"),
    (P3, "portfolio-intel,m4,lane-pm",
     "M4 launch demo delivered to stakeholders. Retrospective scheduled. Epic closed. bd remember portfolio-intel-shipped with what shipped + open followups.",
     "[M4] Launch demo + retro + bd remember shipped state"),
]

print(f"Creating {len(tasks)} tasks...")
ok, fail = 0, 0
for parent, labels, desc, title in tasks:
    r = mk(parent, labels, desc, title)
    if r:
        ok += 1
        print(f"  ok  {r}  {title[:70]}")
    else:
        fail += 1
print(f"\nCreated {ok}, failed {fail}")
